global:
  seed: 888
  RNG_NAMESPACE: 20260115
  generation_type: 'wan_conditional'
  mode: 'sample'
  data_model: 'ar'  
  T: 1
  output_dir: 'src/generation/output/'
  time_emb_dim: 16
  chunk_size_sampler: 16
  debiased_conditioning: False
  num_gen_samples: 128 
  num_conditionings: 512 
data_KS:
  data_file_name: 'data/ks_trajectories_512.h5'
  training_samples: 600
  n_x: 72
  n_y: 6
  d: 2 
data_AR:
  y_nsamples: 6000   
  x_nsamples: 50    
  test_samples: 20048  
  n_x: 300          
  n_y: 5           
  d: 2 
train_denoiser:
  batch_size: 32 
  total_train_steps: 50_000 
  eval_every_steps: 100 
  metric_aggregation_steps: 100 
  save_interval_steps: 25_000 
  num_batches_per_eval: 10 
  max_to_keep: 10
  beta_min: 0.1
  beta_max: 20 
  norm_guide_strength: 1.0
  ema_decay: 0.95
  clip_min: 1e-3 
UNET:
  out_channels: 2
  num_channels: 32,64 #32,64,128
  downsample_ratio: 2,2 #2,2,2
  num_blocks: 6
  noise_embed_dim: 128
  use_attention: True
  num_heads: 8
  use_position_encoding: False
  dropout_rate: 0.0
optimizer:
  init_value: 0.0
  peak_value: 1e-3
  warmup_steps: 1_000
  decay_steps: 990_000
  end_value: 1e-6
  clip_norm: 1.0
  clip_gradient: 1.0
  use_clip_gradient: False
exp_tspan:
  num_steps: 256
  end_sigma: 1e-2 #not defined specifically in the paper
ema:
  ema_decay: 0.999
  use_ema_eval: True
wandb:
  use_wandb: False
metrics: 
  log_ema_metrics_every: 500
  log_train_metrics_every: 50
  epsilon: 1e-5










